/**
 * Reads WASM binaries and JS codec sources from @jsquash packages and
 * generates a TypeScript file with:
 *   - base64-encoded WASM constants
 *   - JS codec source strings (emscripten factories + oxipng wasm-bindgen)
 *
 * The JS sources are embedded as strings so that at runtime we can evaluate
 * them lazily via new Function(), avoiding esbuild bundling the emscripten
 * IIFEs which crash in Figma's restricted sandbox.
 */
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

// ── WASM binaries ───────────────────────────────────────────────────

const wasmFiles = [
  {
    name: 'MOZJPEG_ENC_WASM',
    path: resolve(root, 'node_modules/@jsquash/jpeg/codec/enc/mozjpeg_enc.wasm'),
  },
  {
    name: 'MOZJPEG_DEC_WASM',
    path: resolve(root, 'node_modules/@jsquash/jpeg/codec/dec/mozjpeg_dec.wasm'),
  },
  {
    name: 'OXIPNG_WASM',
    path: resolve(root, 'node_modules/@jsquash/oxipng/codec/pkg/squoosh_oxipng_bg.wasm'),
  },
];

// ── JS codec sources ────────────────────────────────────────────────

const jsFiles = [
  {
    name: 'MOZJPEG_DEC_JS',
    path: resolve(root, 'node_modules/@jsquash/jpeg/codec/dec/mozjpeg_dec.js'),
  },
  {
    name: 'MOZJPEG_ENC_JS',
    path: resolve(root, 'node_modules/@jsquash/jpeg/codec/enc/mozjpeg_enc.js'),
  },
  {
    name: 'OXIPNG_JS',
    path: resolve(root, 'node_modules/@jsquash/oxipng/codec/pkg/squoosh_oxipng.js'),
  },
];

let output = `// Auto-generated by scripts/encode-wasm.mjs — do not edit manually.\n\n`;

// Emit WASM base64 constants
for (const { name, path } of wasmFiles) {
  const bytes = readFileSync(path);
  const b64 = bytes.toString('base64');
  output += `export const ${name}_BASE64 = "${b64}";\n\n`;
  console.log(`  ${name}: ${bytes.length} bytes → ${b64.length} chars base64`);
}

// Emit JS codec source strings
for (const { name, path } of jsFiles) {
  const src = readFileSync(path, 'utf8');
  // Escape backticks and ${} for template literal embedding
  const escaped = src.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  output += `export const ${name}_SOURCE = \`${escaped}\`;\n\n`;
  console.log(`  ${name}: ${src.length} chars JS source`);
}

// Emit base64 decoder helper
output += `export function base64ToArrayBuffer(base64: string): ArrayBuffer {\n`;
output += `  const binary = atob(base64);\n`;
output += `  const bytes = new Uint8Array(binary.length);\n`;
output += `  for (let i = 0; i < binary.length; i++) {\n`;
output += `    bytes[i] = binary.charCodeAt(i);\n`;
output += `  }\n`;
output += `  return bytes.buffer;\n`;
output += `}\n`;

const outPath = resolve(root, 'src/wasm-data.ts');
writeFileSync(outPath, output);
console.log(`\nWrote ${outPath} (${(output.length / 1024).toFixed(0)} KB)`);
